### ISSUE TITLE
DeserializationException 

### ISSUE THREAD

**Issue by suryasinghp** [dpalinic/public-transportation-services#8] opened 2017-06-30 11:21 UTC
Hi i was trying to run your example but facing a 'DeserializationException' exception-- 
```
{
    "name": "DeserializationException",
    "detail": "Unexpected character ('-' (code 45)) in numeric value: expected digit (0-9) to follow 
     minus sign, for valid numeric value\n at [Source: akka.util.ByteIterator$MultiByteArrayIterator$$anon$2@74ae8e16; line: 1, column: 3]"
}
```
I was trying to run following example -

**URL**
POST http://localhost:9000/api/client/registration

**Request Body**
```
{
    "company": "Digital Cat",
    "firstName": "Damir",
    "lastName": "Palinic",
    "email": "damir@palinic.com",
    "username": "dpalinic",
    "password": "test12345"
 }
```
am i missing something?

**Comment by dpalinic** [comment] 2017-06-30 11:24
@dave493 , let me try to checkout project from start and try to reproduce this. I've never seen this message before to be honest.

**Comment by suryasinghp** [comment] 2017-06-30 11:27
Ok 👍

**Comment by dpalinic** [comment] 2017-06-30 11:36
@dave493 , I just did everything from scratch and was not able to reproduce this:

1. `git clone git@github.com:dpalinic/lagom-jwt-authentication.git`
2. `cd lagom-jwt-authentication`
3. `sbt`
4. `runAll`
5. In the separate tab, connect to cassandra `cqlsh localhost 4000`
6. Import db schema `source '/path/to/lagom-jwt-authentication/identity-impl/src/main/resources/db/migration/cassandra/V1.0__db_schema.cql'` 
7. `curl --data '{     "company": "Digital Cat",     "firstName": "Damir",     "lastName": "Palinic",     "email": "damir@palinic.com",     "username": "dpalinic",     "password": "test12345"  }' http://localhost:9000/api/client/registration`
8. Response: `{"id":"46998b0d-d68b-424d-8fd1-d4465b6ed840"}`

Do you have a full stack trace by a chance so I can check where that happened in the code exactly?

**Comment by suryasinghp** [comment] 2017-06-30 11:37
Yeah
```
[error] identity-service - Exception in RestCallIdImpl(POST,/api/client/registration)
com.lightbend.lagom.scaladsl.api.transport.DeserializationException: Unexpected character ('-' (code 45)) in numeric value: expected digit (0-9) to follow minus sign, for valid numeric value
 at [Source: akka.util.ByteIterator$MultiByteArrayIterator$$anon$2@5b81f15a; line: 1, column: 3]
	at com.lightbend.lagom.scaladsl.api.transport.DeserializationException$.apply(Exceptions.scala:306) ~[lagom-scaladsl-api_2.11-1.3.4.jar:1.3.4]
	at com.lightbend.lagom.scaladsl.api.deser.MessageSerializer$$anon$1$JsValueDeserializer$.deserialize(MessageSerializer.scala:143) ~[lagom-scaladsl-api_2.11-1.3.4.jar:1.3.4]
	at com.lightbend.lagom.scaladsl.api.deser.MessageSerializer$$anon$1$JsValueDeserializer$.deserialize(MessageSerializer.scala:139) ~[lagom-scaladsl-api_2.11-1.3.4.jar:1.3.4]
	at com.lightbend.lagom.scaladsl.api.deser.LowPriorityMessageSerializerImplicits$$anon$5$JsValueFormatDeserializer.deserialize(MessageSerializer.scala:247) ~[lagom-scaladsl-api_2.11-1.3.4.jar:1.3.4]
	at com.lightbend.lagom.scaladsl.api.deser.LowPriorityMessageSerializerImplicits$$anon$5$JsValueFormatDeserializer.deserialize(MessageSerializer.scala:245) ~[lagom-scaladsl-api_2.11-1.3.4.jar:1.3.4]
	at com.lightbend.lagom.internal.scaladsl.client.ScaladslServiceApiBridge$class.negotiatedDeserializerDeserialize(ScaladslServiceApiBridge.scala:77) ~[lagom-scaladsl-client_2.11-1.3.4.jar:1.3.4]
	at com.lightbend.lagom.internal.scaladsl.server.ScaladslServiceRouter.negotiatedDeserializerDeserialize(ScaladslServiceRouter.scala:25) ~[lagom-scaladsl-server_2.11-1.3.4.jar:1.3.4]
	at com.lightbend.lagom.internal.scaladsl.server.ScaladslServiceRouter.negotiatedDeserializerDeserialize(ScaladslServiceRouter.scala:25) ~[lagom-scaladsl-server_2.11-1.3.4.jar:1.3.4]
	at com.lightbend.lagom.internal.server.ServiceRouter$$anonfun$com$lightbend$lagom$internal$server$ServiceRouter$$handleServiceCall$1.apply(ServiceRouter.scala:147) ~[lagom-server_2.11-1.3.4.jar:1.3.4]
	at com.lightbend.lagom.internal.server.ServiceRouter$$anonfun$com$lightbend$lagom$internal$server$ServiceRouter$$handleServiceCall$1.apply(ServiceRouter.scala:138) ~[lagom-server_2.11-1.3.4.jar:1.3.4]
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('-' (code 45)) in numeric value: expected digit (0-9) to follow minus sign, for valid numeric value
 at [Source: akka.util.ByteIterator$MultiByteArrayIterator$$anon$2@5b81f15a; line: 1, column: 3]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1586) ~[jackson-core-2.7.8.jar:2.7.8]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:521) ~[jackson-core-2.7.8.jar:2.7.8]
	at com.fasterxml.jackson.core.base.ParserBase.reportUnexpectedNumberChar(ParserBase.java:1069) ~[jackson-core-2.7.8.jar:2.7.8]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleInvalidNumberStart(UTF8StreamJsonParser.java:2753) ~[jackson-core-2.7.8.jar:2.7.8]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._parseNegNumber(UTF8StreamJsonParser.java:1414) ~[jackson-core-2.7.8.jar:2.7.8]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:837) ~[jackson-core-2.7.8.jar:2.7.8]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:748) ~[jackson-core-2.7.8.jar:2.7.8]
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3847) ~[jackson-databind-2.7.8.jar:2.7.8]
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3765) ~[jackson-databind-2.7.8.jar:2.7.8]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2050) ~[jackson-databind-2.7.8.jar:2.7.8]
[error] identity-service - Exception in RestCallIdImpl(POST,/api/client/registration)
```

**Comment by suryasinghp** [comment] 2017-06-30 11:42
I am using postman .With curl it is working fine

**Comment by dpalinic** [comment] 2017-06-30 11:56
That's odd @dave493 . Can you save that postman call and share it with me please (postman should generate url which you can send to me)?

**Comment by dpalinic** [comment] 2017-06-30 12:00
@dave493 , I was able to reproduce it with postman but I put a minus character inside the request body (in front of the password for example):

```
{
	"company": "Digital Cat",
	"firstName": "Damir",
	"lastName": "Palinic",
	"email": "ani@palinic.com",
	"username": "apalinic",
-	"password": "test12345"
}
```
Response:

```json
{
    "name": "DeserializationException",
    "detail": "Unexpected character ('-' (code 45)): was expecting double-quote to start field name\n at [Source: akka.util.ByteIterator$ByteArrayIterator$$anon$1@4ea94bc2; line: 7, column: 2]"
}
```

Can you check your request body? Maybe you put the minus sign somewhere by a mistake?

**Comment by dpalinic** [comment] 2017-06-30 12:04
In the other hand, this is not exactly the same error you had. If you can provide postman collection that would be helpful.

**Comment by suryasinghp** [comment] 2017-06-30 13:09
I have checked it again ..actually i was passing the wrong types .. it is working fine .. thanks

**Comment by dpalinic** [comment] 2017-06-30 13:16
Great. I'll close the issue now.

**Closed as completed by dpalinic** 2017-06-30 13:16 UTC
